name: Build (All platforms)

on:
  workflow_dispatch:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Update Libraries
      run: |
        bash updatelibs.sh
    - name: Build
      run: |
        bash buildlibs.sh ci
    
    - uses: actions/upload-artifact@v3
      with:
        name: ios-simulator
        path: ./bin/ios/simulator
    - uses: actions/upload-artifact@v3
      with:
        name: ios-device
        path: ./bin/ios/device

    - uses: actions/upload-artifact@v3
      with:
        name: macos
        path: ./bin/macos